config:
  validation: true
  warningsAsErrors: false
  excludes: ""

# Custom Architecture Rules
clean-architecture:
  active: true
  CleanArchitectureViolation:
    active: true
  DomainLayerImpurity:
    active: true
  UseCaseNaming:
    active: true
  RepositoryInterface:
    active: true

# Standard Detekt rules
complexity:
  active: true
  CyclomaticComplexMethod:
    threshold: 15
  LongMethod:
    threshold: 60

naming:
  active: true
  ClassNaming:
    classPattern: '[A-Z][a-zA-Z0-9]*'
  FunctionNaming:
    functionPattern: '[a-z][a-zA-Z0-9]*'
    excludeClassPattern: '^.*Test$'

style:
  active: true
  MaxLineLength:
    maxLineLength: 120

potential-bugs:
  active: true

performance:
  active: true

exceptions:
  active: true