name: PR Validation

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened ]

jobs:
  architecture-check:
    name: Architecture Validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Run Detekt with Custom Rules
        run: ./gradlew detekt --continue

      - name: Run ArchUnit Tests
        run: ./gradlew test --tests "*ArchitectureTest*" --tests "*ModuleBoundaryTest*"

      - name: Generate Architecture Report
        if: always()
        run: |
          ./gradlew mergeDetektSarif || true
          ./gradlew generateArchitectureReport || true

      - name: Upload SARIF to GitHub
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: build/reports/detekt/merged.sarif
        continue-on-error: true

      - name: Upload Architecture Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: architecture-reports
          path: |
            build/reports/detekt/
            build/reports/tests/
            build/reports/architecture/
          retention-days: 7

  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Run Android Lint
        run: ./gradlew lint

      - name: Check for TODO comments
        run: |
          if grep -r "TODO" --include="*.kt" --include="*.java" --exclude-dir=".git" --exclude-dir="build" .; then
            echo "❌ TODO comments found. Please resolve before merging."
            exit 1
          fi

  build-check:
    name: Build Verification
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Generate Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/build/reports/tests/
            **/build/test-results/
          retention-days: 7